version: "3.7"                    

services:                         
  noname-mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver-noname
    restart: always
    hostname: mssql
    environment: 
      SA_PASSWORD: qN&d$c(Q4P9Q$Lzf #Thiết lập password
      ACCEPT_EULA: 'Y'
      # Express: 

    volumes:
      - mssqlvolume:/var/opt/mssql/data # thư mục lưu DB
      # - ./bk:/var/opt/mssql/backup
    ports:
      - "1433:1433"     
                        
volumes:                                
    mssqlvolume:        
      name: sqlserver-cryptoNoName
                    
run: docker up -d